aws_region: us-east-1
aws_profile: root
elastic_ip: 107.20.242.17

vpc_name: "jenkins-{{ aws_region }}-vpc"
vpc_cidr: 10.0.0.0/16
vpc_subnets:
  private-1:
    cidr: 10.0.1.0/24
    az: "{{ aws_region }}b"
  private-2:
    cidr: 10.0.2.0/24
    az: "{{ aws_region }}c"
vpc_security_groups:
  - name: ssh
    description: "Open SSH port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 22
  - name: https
    description: "Open HTTPS port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 443
  - name: http
    description: "Open HTTP port 22"
    rules:
      - proto: tcp
        cidr_ip: 0.0.0.0/0
        ports:
          - 80

ec2_instance_type: t2.micro
ec2_image: ami-0817d428a6fb68645
### don't change

r53_zone: apurvamathur.me
r53_record: jenkins.apurvamathur.me

keypair: "awsKeyPair"
ansible_ssh_private_key_file: ~/.ssh/awsKeyPair

### don't change
app: jenkins
### don't change